"""empty message

Revision ID: 84103317f1ad
Revises: 1aae041aa4cf
Create Date: 2021-04-20 09:33:22.807917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84103317f1ad'
down_revision = '1aae041aa4cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
