"""empty message

Revision ID: f47d121d8838
Revises: 84103317f1ad
Create Date: 2021-04-20 09:37:30.869679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47d121d8838'
down_revision = '84103317f1ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
